apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: joao0212/monitoring-mutants:v5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: SCYLLADB_URI
            value: scylladb-service:9042
          - name: SCYLLADB_DATACENTER
            value: datacenter1
          - name: SCYLLA_KEYSPACE
            value: catalog